variables:
  CONTAINER_TEST_IMAGE: psono-docker.jfrog.io/psono/psono-admin-client:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: psono-docker.jfrog.io/psono/psono-admin-client:latest

stages:
  - test
  - build
  - release
  - deploy

test-unittests:
  except:
    - schedules
  stage: test
  image: psono-docker.jfrog.io/ubuntu:22.04
  script:
    - sh ./var/build-ubuntu.sh
    - npm test -- --coverage
#    - apt-get install -y --no-install-recommends xvfb x11vnc fluxbox xterm
#    - curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
#    - apt-get update
#    - apt-get install -y google-chrome-stable
#    - karma start ./unittests/karma-chrome-headless.conf.js


test-vulnerability-scan:
  except:
    - schedules
  stage: test
  image: psono-docker.jfrog.io/node:lts-alpine
  script:
    - npm audit --audit-level high --json --only=prod
  allow_failure: true

#test-linter:
#  except:
#    - schedules
#  stage: test
#  image: psono-docker.jfrog.io/ubuntu:22.04
#  script:
#    - sh ./var/build-ubuntu.sh
#    - cat ./build/firefox/manifest.json
#    - addons-linter --help
#    - addons-linter ./build/firefox


test-upload-translations:
  stage: test
  image: psono-docker.jfrog.io/python:3
  script:
    - pip install requests
    - python3 var/sync_translations.py
  only:
    - develop


build-docker-image:
  except:
    - schedules
  stage: build
  image: psono-docker.jfrog.io/ubuntu:22.04
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - sh ./var/download_translations_from_artifactory.sh
    - sh ./var/build-ubuntu.sh
    - curl -fSL "https://psono.jfrog.io/artifactory/generic-local/docker/docker-20.10.17.tgz" -o docker.tgz && echo "969210917b5548621a2b541caf00f86cc6963c6cf0fb13265b9731c3b98974d9 *docker.tgz" | sha256sum -c - && tar -xzvf docker.tgz && mv docker/* /usr/local/bin/ && rm -Rf docker && rm docker.tgz
    - docker info
    - echo $CI_JOB_TOKEN | docker login --username=gitlab-ci-token --password-stdin registry.gitlab.com
    - echo $artifactory_credentials | docker login --username=gitlab --password-stdin psono-docker.jfrog.io
    - docker build -t $CONTAINER_TEST_IMAGE --pull .
    - docker push $CONTAINER_TEST_IMAGE
    - curl -fL https://getcli.jfrog.io | sh
    - ./jfrog config add rt-server-1 --artifactory-url=https://psono.jfrog.io/psono --user=gitlab --password=$artifactory_credentials --overwrite
    - ./jfrog rt sp "docker/psono/psono-admin-client/$CI_COMMIT_REF_NAME/manifest.json" "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME;CI_COMMIT_SHA=$CI_COMMIT_SHA;CI_COMMIT_URL=$CI_PROJECT_URL/commit/$CI_COMMIT_SHA;CI_PROJECT_ID=$CI_PROJECT_ID;CI_PROJECT_NAME=$CI_PROJECT_NAME;CI_PROJECT_NAMESPACE=$CI_PROJECT_NAMESPACE;CI_PROJECT_URL=$CI_PROJECT_URL;CI_PIPELINE_ID=$CI_PIPELINE_ID;CI_PIPELINE_URL=$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID;CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME;CI_JOB_ID=$CI_JOB_ID;CI_JOB_URL=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID;CI_JOB_NAME=$CI_JOB_NAME;CI_JOB_STAGE=$CI_JOB_STAGE;CI_RUNNER_ID=$CI_RUNNER_ID;GITLAB_USER_ID=$GITLAB_USER_ID;CI_SERVER_VERSION=$CI_SERVER_VERSION"
    - ./jfrog rt sp "docker/psono/psono-admin-client/$CI_COMMIT_REF_NAME/manifest.json" "CI_COMMIT_TAG=$CI_COMMIT_TAG" || true
  only:
    - branches@psono/psono-admin-client
    - tags@psono/psono-admin-client


build-webclient:
  except:
    - schedules
  stage: build
  image: psono-docker.jfrog.io/ubuntu:22.04
  script:
    - sh ./var/download_translations_from_artifactory.sh
    - sh ./var/build-ubuntu.sh
    - sh ./var/package-webclient.sh
    - curl -fL https://getcli.jfrog.io | sh
    - ./jfrog config add rt-server-1 --artifactory-url=https://psono.jfrog.io/psono --user=gitlab --password=$artifactory_credentials --overwrite
    - ./jfrog rt u --target-props="CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME;CI_COMMIT_SHA=$CI_COMMIT_SHA;CI_COMMIT_URL=$CI_PROJECT_URL/commit/$CI_COMMIT_SHA;CI_PROJECT_ID=$CI_PROJECT_ID;CI_PROJECT_NAME=$CI_PROJECT_NAME;CI_PROJECT_NAMESPACE=$CI_PROJECT_NAMESPACE;CI_PROJECT_URL=$CI_PROJECT_URL;CI_PIPELINE_ID=$CI_PIPELINE_ID;CI_PIPELINE_URL=$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID;CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME;CI_JOB_ID=$CI_JOB_ID;CI_JOB_URL=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID;CI_JOB_NAME=$CI_JOB_NAME;CI_JOB_STAGE=$CI_JOB_STAGE;CI_RUNNER_ID=$CI_RUNNER_ID;GITLAB_USER_ID=$GITLAB_USER_ID;CI_SERVER_VERSION=$CI_SERVER_VERSION" /builds/psono/psono-admin-client/build/psono.webclient.zip psono/admin-client/$CI_COMMIT_REF_NAME/webclient.zip
    - ./jfrog rt sp "psono/admin-client/$CI_COMMIT_REF_NAME/webclient.zip" "CI_COMMIT_TAG=$CI_COMMIT_TAG" || true
    - mv /builds/psono/psono-admin-client/build ../
    - rm -Rf *
    - rm -Rf .* 2> /dev/null || true
    - mv ../build/* ./
  artifacts:
    name: "webclient_$CI_COMMIT_REF_NAME"
    paths:
    - ./*
  only:
    - branches@psono/psono-admin-client
    - tags@psono/psono-admin-client

release-artifacts:
  except:
    - schedules
  stage: release
  image: psono-docker.jfrog.io/ubuntu:22.04
  script:
    - apt-get update
    - apt-get install -y curl
    - curl -fL https://getcli.jfrog.io | sh
    - ./jfrog config add rt-server-1 --artifactory-url=https://psono.jfrog.io/psono --user=gitlab --password=$artifactory_credentials --overwrite
#    - ./jfrog rt cp --flat psono/admin-client/$CI_COMMIT_REF_NAME/firefox-extension.zip psono/admin-client/latest/
#    - ./jfrog rt cp --flat psono/admin-client/$CI_COMMIT_REF_NAME/chrome-extension.zip psono/admin-client/latest/
    - ./jfrog rt cp --flat psono/admin-client/$CI_COMMIT_REF_NAME/webclient.zip psono/admin-client/latest/
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


release-docker:
  except:
    - schedules
  stage: release
  image: psono-docker-enterprise.jfrog.io/docker:20.10.17-git
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - echo $CI_JOB_TOKEN | docker login --username=gitlab-ci-token --password-stdin registry.gitlab.com
    - echo $artifactory_credentials | docker login --username=gitlab --password-stdin psono-docker.jfrog.io
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


#deploy-security-scan-image:
#  except:
#    - schedules
#  stage: deploy
#  image: psono-docker-enterprise.jfrog.io/docker:20.10.17-git
#  services:
#    - name: docker:20-dind
#      alias: docker
#      command: ["--tls=false"]
#  variables:
#    DOCKER_DRIVER: overlay2
#    DOCKER_HOST: tcp://docker:2375/
#    DOCKER_TLS_CERTDIR: ""
#  script:
#    - docker info
#    - echo $artifactory_credentials | docker login --username=gitlab --password-stdin psono-docker.jfrog.io
#    - echo $docker_hub_credentials | docker login --username=psonogitlab --password-stdin
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker tag $CONTAINER_TEST_IMAGE psono/security-scans:psono-admin-client-ce-$CI_COMMIT_REF_NAME
#    - docker push psono/security-scans:psono-admin-client-ce-$CI_COMMIT_REF_NAME


deploy-docker:
  except:
    - schedules
  stage: deploy
  image: psono-docker-enterprise.jfrog.io/docker:20.10.17-git
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $artifactory_credentials | docker login --username=gitlab --password-stdin psono-docker.jfrog.io
    - echo $docker_hub_credentials | docker login --username=psonogitlab --password-stdin
    - sh ./var/deploy-docker.sh
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


deploy-github:
  except:
    - schedules
  stage: deploy
  image: psono-docker-enterprise.jfrog.io/docker:20.10.17-git
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - sh ./var/deploy-github.sh
  environment:
    name: github
    url: https://github.com/psono/psono-admin-client
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


#deploy-chrome:
#  except:
#    - schedules
#  stage: deploy
#  image: psono-docker.jfrog.io/ubuntu:22.04
#  script:
#    - sh ./var/build-ubuntu.sh
#    - sh ./var/deploy-chrome-extension.sh
#  environment:
#    name: chrome-webstore
#    url: https://chrome.google.com/webstore/detail/psonopw/eljmjmgjkbmpmfljlmklcfineebidmlo
#  only:
#    - /^v[0-9]*\.[0-9]*\.[0-9]*$/
#
#
#deploy-firefox:
#  except:
#    - schedules
#  stage: deploy
#  image: psono-docker.jfrog.io/ubuntu:22.04
#  script:
#    - sh ./var/build-ubuntu.sh
#    - sh ./var/deploy-firefox-extension.sh
#  environment:
#    name: firefox-webstore
#    url: https://addons.mozilla.org/de/firefox/addon/psono-pw-password-manager/
#  only:
#    - /^v[0-9]*\.[0-9]*\.[0-9]*$/

deploy-changelog:
  except:
    - schedules
  stage: deploy
  image: psono-docker.jfrog.io/ubuntu:22.04
  script:
    - sh ./var/deploy_changelog.sh
  environment:
    name: static.psono.com
    url: https://static.psono.com/gitlab.com/psono/psono-admin-client/changelog.json
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/


deploy-nightlyartifacts:
  except:
    - schedules
  stage: release
  image: psono-docker.jfrog.io/ubuntu:22.04
  script:
    - sh ./var/deploy_nightlyartifacts.sh
  environment:
    name: static.psono.com
    url: https://get.psono.com/psono/psono-admin-client/nightly/adminclient.zip
  only:
    - develop


deploy-releaseartifacts:
  except:
    - schedules
  stage: release
  image: psono-docker.jfrog.io/ubuntu:22.04
  script:
    - sh ./var/deploy_releaseartifacts.sh
  environment:
    name: static.psono.com
    url: https://get.psono.com/psono/psono-admin-client/latest/adminclient.zip
  only:
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/
